In [14]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

np.random.seed(42)

In [15]:
#Electric Vehicle Population Data as of today
df = pd.read_csv('datasets/Electric_Vehicle_Population_Data.csv')

In [16]:
df.head()

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Base MSRP,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 Census Tract
0,KM8K33AGXL,King,Seattle,WA,98103.0,2020,HYUNDAI,KONA,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,258,0,43.0,249675142,POINT (-122.34301 47.659185),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303300e+10
1,1C4RJYB61N,King,Bothell,WA,98011.0,2022,JEEP,GRAND CHEROKEE,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,25,0,1.0,233928502,POINT (-122.20578 47.762405),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.303302e+10
2,1C4RJYD61P,Yakima,Yakima,WA,98908.0,2023,JEEP,GRAND CHEROKEE,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,25,0,14.0,229675939,POINT (-120.6027202 46.5965625),PACIFICORP,5.307700e+10
3,5YJ3E1EA7J,King,Kirkland,WA,98034.0,2018,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,215,0,45.0,104714466,POINT (-122.209285 47.71124),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.303302e+10
4,WBY7Z8C5XJ,Thurston,Olympia,WA,98501.0,2018,BMW,I3,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,97,0,22.0,185498386,POINT (-122.89692 47.043535),PUGET SOUND ENERGY INC,5.306701e+10

In [17]:
df.shape

(150482, 17)

In [18]:
#Month on month electric vehicle data
ev_pop_per_month = pd.read_csv('datasets/Electric_Vehicle_Population_Size_History.csv')

In [19]:
ev_pop_per_month.head(100)

,Date,Plug-In Hybrid Electric Vehicle (PHEV) Count,Battery Electric Vehicle (BEV) Count,Electric Vehicle (EV) Total
0,January 31 2017,7687,14738,22425
1,February 28 2017,7888,15206,23094
2,March 31 2017,8092,15596,23688
3,April 30 2017,8286,16104,24390
4,May 31 2017,8497,16569,25066
...,...,...,...,...
76,May 31 2023,31651,105040,136691
77,June 30 2023,32497,108557,141054
78,July 31 2023,33081,112115,145196
79,August 31 2023,33864,117403,151267
80,September 30 2023,34434,119396,153830

In [20]:
df = pd.read_csv('datasets/Electric_Vehicle_Population_Size_History_By_County.csv')

In [21]:
#Filtering for just Washington
df = df[df.State == 'WA']

In [22]:
df.head()

,Date,County,State,Vehicle Primary Use,Battery Electric Vehicles (BEVs),Plug-In Hybrid Electric Vehicles (PHEVs),Electric Vehicle (EV) Total,Non-Electric Vehicle Total,Total Vehicles,Percent Electric Vehicles
0,June 30 2020,Pend Oreille,WA,Passenger,7,6,13,9241,9254,0.14
1,July 31 2017,Columbia,WA,Truck,0,0,0,1533,1533,0.00
8,May 31 2021,Jefferson,WA,Truck,0,0,0,9615,9615,0.00
12,June 30 2019,Pend Oreille,WA,Truck,0,0,0,5731,5731,0.00
15,May 31 2021,Clark,WA,Truck,0,0,0,84179,84179,0.00

In [23]:
df = df.sort_values(by='Date')
df.head()

,Date,County,State,Vehicle Primary Use,Battery Electric Vehicles (BEVs),Plug-In Hybrid Electric Vehicles (PHEVs),Electric Vehicle (EV) Total,Non-Electric Vehicle Total,Total Vehicles,Percent Electric Vehicles
18171,April 30 2017,Mason,WA,Truck,0,0,0,19240,19240,0.00
9020,April 30 2017,King,WA,Passenger,9556,3882,13438,1378481,1391919,0.97
2277,April 30 2017,Asotin,WA,Truck,0,0,0,6503,6503,0.00
6400,April 30 2017,Chelan,WA,Passenger,55,31,86,51694,51780,0.17
563,April 30 2017,Asotin,WA,Passenger,6,2,8,12342,12350,0.06

In [26]:
fuel_stations = pd.read_csv('datasets/alt_fuel_stations.csv')
fuel_stations.head()

/var/folders/v1/kyy1qs715rbg2rqbmr3z3rb40000gn/T/ipykernel_10598/1886869407.py:1: DtypeWarning: Columns (14,15,16,20,31,33,34,39,41,43,46,49,52,57,58,59,60,61,62,65,67,69,70,71) have mixed types. Specify dtype option on import or set low_memory=False.
  fuel_stations = pd.read_csv('datasets/alt_fuel_stations.csv')

,Fuel Type Code,Station Name,Street Address,Intersection Directions,City,State,ZIP,Plus4,Station Phone,Status Code,...,Restricted Access,RD Blends,RD Blends (French),RD Blended with Biodiesel,RD Maximum Biodiesel Level,NPS Unit Name,CNG Station Sells Renewable Natural Gas,LNG Station Sells Renewable Natural Gas,Maximum Vehicle Class,EV Workplace Charging
0,CNG,Arkansas Oklahoma Gas Corp,2100 S Waldron Rd,NaN,Fort Smith,AR,72903,NaN,479-783-3181,E,...,False,NaN,NaN,NaN,NaN,NaN,False,NaN,MD,NaN
1,CNG,Clean Energy - Logan International Airport,1000 Cottage St Ext,"From Route 1, take the first exit after Callah...",East Boston,MA,02128,NaN,866-809-4869,E,...,False,NaN,NaN,NaN,NaN,NaN,True,NaN,MD,NaN
2,CNG,Clean Energy - Everett - National Grid,16 Rover St,"Rt 16, exit to Rt 99, to Dexter St to Rover. O...",Everett,MA,02149,NaN,866-809-4869,E,...,False,NaN,NaN,NaN,NaN,NaN,False,NaN,HD,NaN
3,CNG,Clean Energy - Greenpoint - National Grid,287 Maspeth Ave,"I-278/Brooklyn Queens Expy, exit onto Vandervo...",Brooklyn,NY,11211,NaN,866-809-4869,E,...,False,NaN,NaN,NaN,NaN,NaN,True,NaN,HD,NaN
4,CNG,Canarsie - National Grid,8424 Ditmas Ave,"From Shore Pkwy, take Rockaway Pkwy N, left on...",Brooklyn,NY,11236,NaN,866-809-4869,E,...,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MD,NaN